//! Roland JC-120, one of its two 60 W solid-state power amplifiers.
//!
//! Read off the MAIN AMP BOARD of the JC-120UT/JT service notes of Sep. 2000.
//! The sheet is `docs/schematics/roland_jc120ut_jt_service_notes_2000.pdf` and
//! the checkpoint is `docs/models/jazz_120.md`. POWER AMP L and POWER AMP R are
//! identical part for part, so this is both of them.
//!
//! **The topology was measured, not read.** Two earlier attempts at this
//! circuit were written from crops and both were wrong, so the nodes here come
//! out of `tools/schematic/trace.py`, which separates junction dots from wires
//! by morphology and joins the wires into electrical nodes. Every connection
//! below is one of those nodes or one of the gaps it found between them.
//!
//! **Not a `PowerSpec`.** `circuits::power` is valve-shaped throughout -- phase
//! inverter, grid leaks, a bias supply, an output transformer -- and this
//! amplifier has none of them. It gets its own module for the same stated
//! reason the 73P's line driver does.
//!
//! The shape, once the nodes are named:
//!
//! ```text
//!            VB ── R91 ── tail ── Q16, Q15 (2SA970 pair) ── R92, R87 ── -VE
//!            │                       │ base                   │
//!  +VE ─R68─R72─ D11                 └─ R88 from the output    └─ Q13 base
//!            │        (a fixed drop in the model -- see `D_RAIL_DROP`)
//!            │
//!            └─ R78 ─ boot ─ R82 ─ n1 ─ R76∥R79 ─ n11 ─ R75 ─ n3 ─ Q13 ─ R83 ─ -VE
//!                      │              │                    │
//!                   C43 to out    Q10 base            Q11 base
//! ```
//!
//! Three things that are worth naming because none of them is guessable:
//!
//! * **C43 bootstraps the collector load.** It is the only connection between
//!   the R78/R82 junction and the output, so the string above Q13 is held a
//!   constant voltage above the output and behaves as a current source.
//! * **Q14 and Q12 are a two-transistor bias spreader**, not a mirror. Q14 sits
//!   across R76 + R75 -- collector on the upper driver's base, emitter on the
//!   lower one's -- and Q12 senses their junction and drives it, which makes
//!   the pair a precise voltage source between the two driver bases. C44's
//!   0.068 µF across the whole thing is the speed-up that carries the audio
//!   past it while the direct voltage stays set.
//! * **Q13 is the voltage amplifier stage**, base straight off the pair's
//!   collector, emitter degenerated by R83.
//!
//! Two figures make this a checked model rather than a plausible one, and both
//! are printed on the sheet:
//!
//! * **the gain.** R88 68 k over R93 3.3 k is `1 + 68/3.3` = 26.7 dB, and the
//!   test points are `+3 dBm, 3.10 Vpp` in and `+29 dBm, 61.8 Vpp` out -- 26 dB.
//! * **the balance.** R97 and R88 are both 68 k, so with C48 blocking R93 at
//!   direct current both bases of the pair see 68 k to ground. That is how a
//!   PNP input pair is balanced, and it is the cross-check that R88 is the
//!   feedback resistor rather than R93.
//!
//! 61.8 Vpp into 8 ohms is 21.85 V rms and 59.7 W, which is Roland's 60 W.
//!
//! **One part is deliberately absent.** D14 and Q17, a 1SS133 and a 2SK381E
//! shunting the input node, are the power-on mute: the JFET is held on while
//! the rails come up and turned off once they have, so that the thump a
//! complementary output stage makes on switch-on does not reach the speaker.
//! It is off whenever there is audio to hear, so modelling it would add a
//! device to every Newton solve to represent an open switch.

use crate::acoustics::speaker::{self, LoadSlots, LoadValues};
use crate::dsp::netlist::{BipolarSpec, Circuit, Fault, Netlist};

/// The speaker terminals.
pub const OUTPUT: &str = "out";
/// The inverting input, where the feedback lands.
pub const FEEDBACK_NODE: &str = "q15_b";
/// The upper driver's base: the top of the bias spreader, and the node the
/// bootstrapped collector load works into.
pub const UPPER_DRIVE: &str = "n1";
/// The lower driver's base, and the voltage amplifier stage's collector.
pub const LOWER_DRIVE: &str = "n3";

// --- devices, all named on the sheet ------------------------------------
const Q_INPUT: BipolarSpec = BipolarSpec::PNP_2SA970_GR;
/// Q13, the voltage amplifier stage.
const Q_VAS: BipolarSpec = BipolarSpec::NPN_2SC2229_O;
/// Q14 and Q12, the bias spreader.
const Q_SPREAD_N: BipolarSpec = BipolarSpec::NPN_2SC1815_GR;
const Q_SPREAD_P: BipolarSpec = BipolarSpec::PNP_2SA1015_GR;
const Q_DRIVER_N: BipolarSpec = BipolarSpec::NPN_2SD669_AC;
const Q_DRIVER_P: BipolarSpec = BipolarSpec::PNP_2SB649_AC;
const Q_OUT_N: BipolarSpec = BipolarSpec::NPN_2SC4386;
const Q_OUT_P: BipolarSpec = BipolarSpec::PNP_2SA1671;
/// D11, a 1N4004 dropping the small-signal supply off +VE.
///
/// **Modelled as a fixed drop rather than as a diode, and that is worth
/// stating.** It is in series with 1.36 k feeding a 47 uF decoupling
/// capacitor, so it carries a near-constant 4.9 mA and never switches while
/// there is audio -- its whole job is the drop and reverse blocking at
/// power-down. As a diode it cost more than it was worth twice over: it put
/// two more nodes on the nonlinear boundary, taking it from 18 to 20 of 31
/// unknowns, and the bootstrap pushes `vb` around enough to make its
/// linearisation switch. Measured at the amplifier's clipping point, taking it
/// out of the nonlinear set was **38 % of the solve time and 74 % of the
/// fallbacks**. The drop is the one the diode model itself settled at, so the
/// operating point does not move.
///
/// What is lost is `+VE`'s own sag reaching `vb`. Nothing: the 1.36 k and the
/// 47 uF put a corner at 2.5 Hz, so the supply ripple was filtered out of this
/// node before it could reach anything anyway.
///
/// APPROXIMATED. See `examples/stutter.rs`, which is the measurement.
const D_RAIL_DROP: f64 = 0.66;

// --- the supply ---------------------------------------------------------
/// DERIVED, and the one number on this board that is not read. No secondary
/// voltage is printed and the parts list gives the transformer only by part
/// number. It comes out of the printed output instead: 61.8 Vpp into 8 ohms
/// needs the rails to clear +-30.9 V plus the output pair's saturation and the
/// drop across the 0.33 ohm emitter resistors, and the 63 V reservoir
/// capacitors put a ceiling on it.
pub const RAIL_VOLTS: f64 = 40.0;
/// ESTIMATED: 3300 uF a side behind a bridge is stiff, and what sag there is
/// belongs to the mains rather than to this board.
const RAIL_OHMS: f64 = 0.5;
const RESERVOIR: f64 = 3300e-6;
/// Between the reservoir capacitor and the output devices' collectors: the
/// capacitor's own ESR, the wiring from the DI board to the TR board, and each
/// transistor's collector ohmic resistance.
///
/// This was absent, and its absence was expensive. With the collectors sitting
/// directly on the reservoir node, a saturating output device is a path of
/// *no* resistance between a stiff supply and a signal node, and Ebers-Moll in
/// saturation drives both junction conductances toward 1e13 S. That is not a
/// hard solve, it is an unconditioned one: measured at the clipping point the
/// stage took 4.18 Newton passes a sample and fell back 2254 times in 9,600
/// samples. With the resistance in, 2.58 passes and **56**.
///
/// ESTIMATED at 50 milliohms -- a 3300 uF electrolytic is about 50 mOhm of ESR
/// on its own and the rail wiring is tens more -- but the model is insensitive
/// to it over the range that is physically arguable: 20 mOhm and 200 mOhm were
/// both measured and the output moved in the third decimal place. It is here
/// because it is real and was missing, not to make a number come out.
const RAIL_WIRING_OHMS: f64 = 0.05;
/// R68 and R72, then D11, into the small-signal supply behind C42.
const RAIL_DROPPER: f64 = 680.0;
const RAIL_DECOUPLING: f64 = 47e-6;

// --- the input pair -----------------------------------------------------
const INPUT_COUPLING: f64 = 0.068e-6; // C49
const INPUT_SERIES: f64 = 6_800.0; // R98
const INPUT_SHUNT: f64 = 68_000.0; // R97
const TAIL_R: f64 = 33_000.0; // R91, from the small-signal supply
const COLLECTOR_LOAD: f64 = 1_500.0; // R92 and R87, to -VE

// --- global feedback ----------------------------------------------------
const FEEDBACK_R: f64 = 68_000.0; // R88
const FEEDBACK_LOWER: f64 = 3_300.0; // R93
const FEEDBACK_BLOCK: f64 = 4.7e-6; // C48

// --- the collector load, and the bootstrap ------------------------------
const LOAD_TOP: f64 = 1_500.0; // R78, from the supply
const LOAD_UPPER: f64 = 6_800.0; // R82, to the upper driver's base
const BOOTSTRAP: f64 = 47e-6; // C43, to the output
/// R76, R79 and R75, the spreader's own divider between the two driver bases.
///
/// **R76 and R79 are both 3.9 k and both sit between the upper driver's base
/// and the sense node**, so the upper leg is 1.95 k and not 3.9 k. R79 was
/// missing here until 2026-09-23, and the consequence was not subtle: with the
/// upper leg twice its real value the spreader held the driver bases 1.48 V
/// apart where a Darlington output stage needs four base-emitter junctions'
/// worth, about 2.4 V. The PNP half of the output stage sat at **-0.34 V of
/// base-emitter bias -- reverse biased, fully off** -- while the NPN half
/// carried the whole 9.6 mA idle on its own.
///
/// So the amplifier was single-ended with a dead zone across every zero
/// crossing: audibly, crossover distortion on a famously clean amplifier, and
/// numerically, an ill-conditioned solve every time the signal passed through
/// zero. Real playing does that constantly at every level, which is why a
/// recorded DI take produced 150,000 fallbacks where a synthetic sine produced
/// 1,400.
///
/// Read off the sheet with `tools/schematic/trace.py`, which found the two
/// junction dots R79 hangs from at (13537, 5363) and (13537, 5582) on page 7
/// of the service notes. DOCUMENTED.
const SPREAD_UPPER_A: f64 = 3_900.0; // R76
const SPREAD_UPPER_B: f64 = 3_900.0; // R79, in parallel with it
const SPREAD_LOWER: f64 = 6_800.0; // R75
/// C44, across the whole spreader: the audio goes past it, the bias does not.
const SPREAD_BYPASS: f64 = 0.068e-6;
/// The two spreader transistors' output capacitances, `Cob`, from their
/// data sheets: 3.5 pF for the 2SA1015 and 2.0 pF for the 2SC1815, both typical
/// at `Vcb = 10 V`.
///
/// **These are here because without them the node between them is not a node.**
/// Q12's collector meets Q14's base and nothing else -- that is what the sheet
/// draws, and it is fine on a board, where every junction has capacitance and
/// every track has stray. In a solver it is a node held only by two
/// reverse-biased junctions' leakage, around 1e-12 S each, so any imbalance
/// between them moves it by a billion volts; measured, `q14_b` reached
/// **-1.06e9 V** as soon as the output stage was biased hard enough to drive
/// the spreader into cutoff at clipping, and the solve went with it -- 43.6
/// Newton passes a sample and thirty-one million fallbacks.
///
/// Five picofarads is nothing at audio, and that is the point: it changes no
/// response anywhere, and it raises that node's conductance from 1e-12 S to
/// about 5e-7 S, which is the difference between an ill-conditioned row and a
/// well-posed one. DOCUMENTED, from the two parts' own data sheets, rather
/// than a number chosen to make the solve behave.
const Q_SPREAD_P_COB: f64 = 3.5e-12;
const Q_SPREAD_N_COB: f64 = 2.0e-12;

// --- the voltage amplifier stage ----------------------------------------
const VAS_EMITTER: f64 = 68.0; // R83
const VAS_COMPENSATION: f64 = 68e-12; // C46

// --- the output stage ---------------------------------------------------
const DRIVER_MILLER: f64 = 150e-12; // C41 and C45
const DRIVER_BLEED: f64 = 330.0; // R69, across the driver emitters
const DRIVER_FEED: f64 = 6.8; // R58 and R59, fusible
const EMITTER_R: f64 = 0.33; // R62 and R63, 5 W
/// R86 and C40, the output network.
const ZOBEL_R: f64 = 6.8;
const ZOBEL_C: f64 = 0.068e-6;

/// The nominal load, which is one 8 ohm driver a side.
pub const SPEAKER_OHMS: f64 = 8.0;

fn complete_netlist(source: f64, load: f64) -> Netlist {
    let mut net = Netlist::new("Roland JC-120 power amplifier");

    // The rails, off the bridge on the DI board, and the small-signal supply
    // that R68, R72 and D11 make from the positive one.
    net.supply("pos", RAIL_OHMS, RAIL_VOLTS)
        .capacitor("pos", "gnd", RESERVOIR)
        .supply("neg", RAIL_OHMS, -RAIL_VOLTS)
        .capacitor("neg", "gnd", RESERVOIR)
        // R68, R72 and D11 as one Thevenin source: the two droppers in series
        // and the diode's settled drop taken off the rail. See `D_RAIL_DROP`.
        .supply("vb", RAIL_DROPPER * 2.0, RAIL_VOLTS - D_RAIL_DROP)
        .capacitor("vb", "gnd", RAIL_DECOUPLING);

    // The input pair. PNP, so the tail comes from above and the collectors
    // work down into -VE. R97 balances R88 at direct current.
    net.input("in", source)
        .capacitor("in", "in_c", INPUT_COUPLING)
        .resistor("in_c", "q16_b", INPUT_SERIES)
        .resistor("q16_b", "gnd", INPUT_SHUNT)
        .resistor("vb", "tail", TAIL_R)
        .bipolar_pnp("q16_c", "q16_b", "tail", Q_INPUT)
        .bipolar_pnp("q15_c", FEEDBACK_NODE, "tail", Q_INPUT)
        .resistor("q16_c", "neg", COLLECTOR_LOAD)
        .resistor("q15_c", "neg", COLLECTOR_LOAD);

    // Global feedback: unity at direct current, `1 + 68/3.3` in the band.
    net.resistor(OUTPUT, FEEDBACK_NODE, FEEDBACK_R)
        .resistor(FEEDBACK_NODE, "fb_low", FEEDBACK_LOWER)
        .capacitor("fb_low", "gnd", FEEDBACK_BLOCK);

    // The collector load, bootstrapped. R78 and R82 from the supply down to
    // the upper driver's base, with C43 holding their junction a constant
    // voltage above the output -- which is what makes the load a current
    // source instead of a resistor to the rail.
    net.resistor("vb", "boot", LOAD_TOP)
        .capacitor("boot", OUTPUT, BOOTSTRAP)
        .resistor("boot", UPPER_DRIVE, LOAD_UPPER);

    // The bias spreader. R76 and R75 divide between the two driver bases; Q14
    // sits across the pair of them and Q12 senses their junction and drives
    // it, so the two bases are held a fixed distance apart. C44 carries the
    // audio straight across.
    net.resistor(UPPER_DRIVE, "n11", SPREAD_UPPER_A)
        .resistor(UPPER_DRIVE, "n11", SPREAD_UPPER_B)
        .resistor("n11", LOWER_DRIVE, SPREAD_LOWER)
        .bipolar_pnp("q14_b", "n11", UPPER_DRIVE, Q_SPREAD_P)
        .bipolar(UPPER_DRIVE, "q14_b", LOWER_DRIVE, Q_SPREAD_N)
        // The two parts' own collector-base capacitance. See `Q_SPREAD_P_COB`.
        .capacitor("q14_b", "n11", Q_SPREAD_P_COB)
        .capacitor("q14_b", UPPER_DRIVE, Q_SPREAD_N_COB)
        .capacitor(UPPER_DRIVE, LOWER_DRIVE, SPREAD_BYPASS);

    // Q13, the voltage amplifier stage: base straight off the pair's
    // collector, emitter degenerated by R83, collector at the bottom of the
    // spreader.
    net.bipolar(LOWER_DRIVE, "q16_c", "q13_e", Q_VAS)
        .resistor("q13_e", "neg", VAS_EMITTER)
        .capacitor("q16_c", LOWER_DRIVE, VAS_COMPENSATION);

    // The drivers, their bleeder, and their Miller capacitors.
    // The rails as the output devices actually see them, a reservoir and some
    // wiring away from where they are made. See `RAIL_WIRING_OHMS`.
    net.resistor("pos", "pos_c", RAIL_WIRING_OHMS)
        .resistor("neg", "neg_c", RAIL_WIRING_OHMS)
        .bipolar("pos_c", UPPER_DRIVE, "drv_n", Q_DRIVER_N)
        .bipolar_pnp("neg_c", LOWER_DRIVE, "drv_p", Q_DRIVER_P)
        .resistor("drv_n", "drv_p", DRIVER_BLEED)
        .capacitor(UPPER_DRIVE, "pos", DRIVER_MILLER)
        .capacitor(LOWER_DRIVE, "neg", DRIVER_MILLER);

    // The output pair on the TR board, through their fusible feeds and the
    // 0.33 ohm emitter resistors the idle current is set across.
    net.resistor("drv_n", "out_n_b", DRIVER_FEED)
        .resistor("drv_p", "out_p_b", DRIVER_FEED)
        .bipolar("pos_c", "out_n_b", "e_n", Q_OUT_N)
        .bipolar_pnp("neg_c", "out_p_b", "e_p", Q_OUT_P)
        .resistor("e_n", OUTPUT, EMITTER_R)
        .resistor("e_p", OUTPUT, EMITTER_R);

    // The output network. The speaker itself is stamped by the caller, because
    // it is either a resistor or a real driver.
    net.resistor(OUTPUT, "zobel", ZOBEL_R)
        .capacitor("zobel", "gnd", ZOBEL_C);
    if load > 0.0 {
        net.resistor(OUTPUT, "gnd", load);
    }

    net
}

pub fn build(source: f64, load: f64) -> Result<Circuit, Fault> {
    complete_netlist(source, load).build(OUTPUT)
}

/// The same amplifier read at a chosen node, for stage-by-stage probing.
pub fn tap(source: f64, load: f64, at: &str) -> Result<Circuit, Fault> {
    complete_netlist(source, load).build(at)
}

/// The same amplifier working into a real driver rather than into 8 ohms of
/// resistance, which is what the acoustics path needs.
///
/// It matters more here than it looks. A loudspeaker's impedance is nothing
/// like the resistor that stands for it -- it rises through resonance and
/// climbs with frequency above it -- and this amplifier has the feedback loop
/// to hold its output voltage across all of that. What changes is the current,
/// and with it where the output pair runs out. Reading the cone rather than
/// the terminals is the whole point of the physical path.
pub fn build_with_speaker(source: f64, load: &LoadValues) -> Result<(Circuit, LoadSlots), Fault> {
    let mut net = complete_netlist(source, 0.0);
    let slots = speaker::stamp(&mut net, OUTPUT, load);
    Ok((net.build(speaker::MOTIONAL)?, slots))
}
